spring.application.name=application
server.address=127.0.0.1
server.port=18430
management.endpoints.web.exposure.include=health,beans
management.endpoint.health.show-details=never
spring.kafka.bootstrap-servers=127.0.0.1:1
spring.kafka.listener.auto-startup=false
